### ISSUE TITLE
UnicodeDecodeError at Statistics Department scraper

### ISSUE THREAD

**Issue by furkansimsekli** [hacettepeoyt/hu-announcement-bot#35]
```
Traceback (most recent call last):
   File "/home/hu-announcement/dev/hu-announcement-bot/src/task.py", line 16, in check_announcements
     news = await department.get_announcements()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/hu-announcement/dev/hu-announcement-bot/src/scraper.py", line 39, in get_announcements
     html_text: str = await resp.text(encoding='utf-8')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/hu-announcement/dev/hu-announcement-bot/.venv/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1086, in text
     return self._body.decode(  # type: ignore[no-any-return,union-attr]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 28541: invalid continuation byte
```

Haven't looked thoroughly yet.

**Comment by furkansimsekli** [comment]
It's probably related with `_fix_invalid_url()` method. Valid pattern logic seems to be "failing" for such urls:
- "https://stat.hacettepe.edu.tr/tr/mat_122_kodlu_dersin_ek_sinav_-821"

If possible, I'll try different solution other than regex. Currently working on it.

**Comment by melikechan** [comment]
Well, the new method seems way better!
Creating that RegEx pattern was "tiring" because there would be other invalid rules. I can say, this is a great "today I learned" function. 😅
